<?php

declare(strict_types=1);

namespace MailPanel\Services;

final class DovecotConfigRenderer
{
    private readonly TlsCertificateInventory $tlsInventory;

    public function __construct(
        private readonly string $generatedRoot,
        private readonly string $vmailRoot,
        private readonly array $databaseConfig,
        private readonly int $vmailUid = 2000,
        private readonly int $vmailGid = 2000,
        private readonly string $passwordScheme = 'BLF-CRYPT',
        private readonly string $defaultTlsCertificate = '/etc/exim4/ssl/mailpanel.pem',
        private readonly string $defaultTlsPrivateKey = '/etc/exim4/ssl/mailpanel.key',
        ?TlsCertificateInventory $tlsInventory = null,
    ) {
        $this->tlsInventory = $tlsInventory ?? new TlsCertificateInventory();
    }

    public function render(): array
    {
        $generatedRoot = $this->safeAbsolutePath($this->generatedRoot, 'generated root');
        $vmailRoot = $this->safeAbsolutePath($this->vmailRoot, 'vmail root');
        $defaultTlsCertificate = $this->safeAbsolutePath($this->defaultTlsCertificate, 'default TLS certificate path');
        $defaultTlsPrivateKey = $this->safeAbsolutePath($this->defaultTlsPrivateKey, 'default TLS private key path');
        $passwordScheme = $this->dovecotAtom($this->passwordScheme, 'password scheme');
        $vmailUid = $this->safeUidGid($this->vmailUid, 'vmail uid');
        $vmailGid = $this->safeUidGid($this->vmailGid, 'vmail gid');

        $content = <<<CONF
# generated by MailPanel
listen = *
protocols = imap pop3 lmtp sieve
ssl = required
ssl_cert = <{$defaultTlsCertificate}
ssl_key = <{$defaultTlsPrivateKey}
disable_plaintext_auth = yes
auth_mechanisms = plain login
mail_location = maildir:{$vmailRoot}/%d/%n
mail_home = {$vmailRoot}/%d/%n
first_valid_uid = {$vmailUid}
last_valid_uid = {$vmailUid}
passdb {
  driver = sql
  args = {$generatedRoot}/active/dovecot/dovecot-sql.conf.ext
}
userdb {
  driver = sql
  args = {$generatedRoot}/active/dovecot/dovecot-sql.conf.ext
}
service auth {
  unix_listener /var/spool/exim4/private/auth {
    mode = 0660
    user = Debian-exim
    group = Debian-exim
  }
}
service stats {
  unix_listener stats-reader {
    user = vmail
    group = vmail
    mode = 0660
  }
}
namespace inbox {
  inbox = yes
  mailbox Drafts {
    auto = subscribe
    special_use = \\Drafts
  }
  mailbox Sent {
    auto = subscribe
    special_use = \\Sent
  }
  mailbox Trash {
    auto = subscribe
    special_use = \\Trash
  }
  mailbox Junk {
    auto = subscribe
    special_use = \\Junk
  }
  mailbox Archive {
    auto = subscribe
    special_use = \\Archive
  }
}
protocol lmtp {
  mail_plugins = \$mail_plugins sieve quota
}
protocol lda {
  mail_plugins = \$mail_plugins sieve quota
  lda_mailbox_autocreate = yes
  lda_mailbox_autosubscribe = yes
}
plugin {
  quota = maildir:User quota
  sieve = file:~/sieve;active=~/sieve/active.sieve
}
CONF;

        foreach ($this->tlsInventory->entries() as $hostname => $paths) {
            $certificate = $this->safeAbsolutePath((string) ($paths['certificate'] ?? ''), 'TLS certificate path');
            $privateKey = $this->safeAbsolutePath((string) ($paths['privatekey'] ?? ''), 'TLS private key path');
            $content .= <<<CONF

local_name {$hostname} {
  ssl_cert = <{$certificate}
  ssl_key = <{$privateKey}
}
CONF;
        }

        $driver = $this->dovecotAtom($this->databaseConfig['driver'] ?? 'mysql', 'database driver');
        $host = $this->dovecotConnectValue($this->databaseConfig['host'] ?? '127.0.0.1', 'database host');
        $port = (int) ($this->databaseConfig['port'] ?? 3306);
        $database = $this->dovecotConnectValue($this->databaseConfig['database'] ?? 'mailpanel', 'database name');
        $username = $this->dovecotConnectValue($this->databaseConfig['username'] ?? 'mailpanel', 'database username');
        $password = $this->dovecotConnectValue($this->databaseConfig['password'] ?? '', 'database password');

        $sql = <<<CONF
driver = {$driver}
connect = host={$host} port={$port} dbname={$database} user={$username} password={$password}
default_pass_scheme = {$passwordScheme}
password_query = SELECT m.email AS user, m.password_hash AS password FROM mailboxes m INNER JOIN domains d ON d.id = m.domain_id AND d.deleted_at IS NULL INNER JOIN tenants t ON t.id = m.tenant_id AND t.deleted_at IS NULL WHERE m.email = '%u' AND m.deleted_at IS NULL AND m.status = 'active' AND COALESCE(m.force_password_change, 0) = 0 AND d.status = 'active' AND d.inbound_enabled = 1 AND {$this->tenantMailAccessSql('t')} AND {$this->mailboxServiceAccessSql()}
user_query = SELECT CONCAT('{$vmailRoot}/', SUBSTRING_INDEX(m.email,'@',-1), '/', SUBSTRING_INDEX(m.email,'@',1)) AS home, {$vmailUid} AS uid, {$vmailGid} AS gid, CONCAT('maildir:{$vmailRoot}/', SUBSTRING_INDEX(m.email,'@',-1), '/', SUBSTRING_INDEX(m.email,'@',1)) AS mail, CONCAT('maildir:storage=', m.quota_mb, 'M') AS quota_rule FROM mailboxes m INNER JOIN domains d ON d.id = m.domain_id AND d.deleted_at IS NULL INNER JOIN tenants t ON t.id = m.tenant_id AND t.deleted_at IS NULL WHERE m.email = '%u' AND m.deleted_at IS NULL AND m.status = 'active' AND COALESCE(m.force_password_change, 0) = 0 AND d.status = 'active' AND d.inbound_enabled = 1 AND {$this->tenantMailAccessSql('t')} AND {$this->mailboxServiceAccessSql()}
CONF;

        return [
            'service' => 'dovecot',
            'path' => $generatedRoot . '/dovecot/dovecot.conf',
            'content' => $content,
            'extras' => [
                [
                    'path' => $generatedRoot . '/dovecot/dovecot-sql.conf.ext',
                    'content' => $sql,
                ],
            ],
        ];
    }

    private function tenantMailAccessSql(string $alias): string
    {
        return TenantLifecyclePolicy::sqlMailAccessCondition($alias);
    }

    private function mailboxServiceAccessSql(): string
    {
        return "(('%s' NOT IN ('imap', 'pop3', 'sieve')) OR ('%s' = 'imap' AND m.imap_enabled = 1) OR ('%s' = 'pop3' AND m.pop3_enabled = 1) OR ('%s' = 'sieve' AND m.managesieve_enabled = 1))";
    }

    private function dovecotAtom(mixed $value, string $label): string
    {
        $value = trim((string) $value);
        if ($value === '' || preg_match('/\A[A-Za-z0-9_.-]+\z/', $value) !== 1) {
            throw new \InvalidArgumentException(sprintf('Invalid %s for Dovecot SQL config.', $label));
        }

        return $value;
    }

    private function dovecotConnectValue(mixed $value, string $label): string
    {
        $value = (string) $value;
        if (preg_match('/[\x00-\x1F\x7F]/', $value) === 1) {
            throw new \InvalidArgumentException(sprintf('Invalid %s for Dovecot SQL config.', $label));
        }

        return str_replace(['\\', ' '], ['\\\\', '\\ '], $value);
    }

    private function safeAbsolutePath(string $path, string $label): string
    {
        $path = rtrim(trim($path), '/\\');
        $normalized = str_replace('\\', '/', $path);
        $isUnixAbsolute = str_starts_with($path, '/') && preg_match('/\A[\/A-Za-z0-9._-]+\z/', $path) === 1;
        $isWindowsAbsolute = preg_match('/\A[A-Za-z]:[\/\\\\A-Za-z0-9._~-]+\z/', $path) === 1;

        if ($path === '' || (!$isUnixAbsolute && !$isWindowsAbsolute) || $this->containsPathTraversal($normalized)) {
            throw new \InvalidArgumentException(sprintf('Invalid %s for Dovecot config.', $label));
        }

        return $path;
    }

    private function containsPathTraversal(string $path): bool
    {
        $segments = array_values(array_filter(explode('/', $path), static fn (string $segment): bool => $segment !== ''));

        return in_array('..', $segments, true);
    }

    private function safeUidGid(int $value, string $label): int
    {
        if ($value < 1 || $value > 65535) {
            throw new \InvalidArgumentException(sprintf('Invalid %s for Dovecot config.', $label));
        }

        return $value;
    }
}
