<?php

declare(strict_types=1);

namespace MailPanel\Services;

final class Fail2banConfigRenderer
{
    public function __construct(
        private readonly string $generatedRoot,
        private readonly bool $webmailEnabled = false,
        private readonly string $webmailLogPath = '/var/www/webmail/data/_data_/_default_/logs/auth.log',
    )
    {
    }

    public function render(): array
    {
        $generatedRoot = $this->safeAbsolutePath($this->generatedRoot, 'generated root');
        $webmailEnabled = $this->webmailEnabled ? 'true' : 'false';
        $webmailLogPath = $this->safeAbsolutePath($this->webmailLogPath, 'webmail log path');
        $webmailFilter = "[Definition]\n"
            . "failregex = ^.*(?:Admin )?Auth failed:\\s*ip=<HOST>\\s+user=.*$\n"
            . "            ^.*(?:Failed login|php: Login failed for).*from <HOST>.*$\n"
            . "ignoreregex =\n";

        $content = <<<CONF
# generated by MailPanel
[dovecot]
enabled = true
backend = systemd
filter = mailpanel-dovecot
journalmatch = _SYSTEMD_UNIT=dovecot.service
maxretry = 5
findtime = 10m
bantime = 1h

[exim-smtp-auth]
enabled = true
backend = systemd
filter = mailpanel-exim-auth
journalmatch = _SYSTEMD_UNIT=exim4.service
maxretry = 5
findtime = 10m
bantime = 1h

[exim-reject]
enabled = true
backend = systemd
filter = mailpanel-exim-reject
journalmatch = _SYSTEMD_UNIT=exim4.service
maxretry = 5
findtime = 10m
bantime = 1h

[webmail-auth]
enabled = {$webmailEnabled}
filter = mailpanel-webmail-auth
logpath = {$webmailLogPath}
maxretry = 5
findtime = 10m
bantime = 1h

[sshd]
enabled = false
maxretry = 5
findtime = 10m
bantime = 1h
CONF;

        return [
            'service' => 'fail2ban',
            'path' => $generatedRoot . '/fail2ban/jail.local',
            'content' => $content,
            'extras' => [
                [
                    'path' => $generatedRoot . '/fail2ban/filter.d/mailpanel-dovecot.conf',
                    'content' => "[Definition]\nfailregex = ^.*rip=<HOST>.*auth failed.*$\nignoreregex =\n",
                ],
                [
                    'path' => $generatedRoot . '/fail2ban/filter.d/mailpanel-exim-auth.conf',
                    'content' => "[Definition]\nfailregex = ^.*SMTP authentication error.*\\[<HOST>\\].*$\nignoreregex =\n",
                ],
                [
                    'path' => $generatedRoot . '/fail2ban/filter.d/mailpanel-exim-reject.conf',
                    'content' => "[Definition]\nfailregex = ^.*rejected RCPT.*\\[<HOST>\\].*$\nignoreregex =\n",
                ],
                [
                    'path' => $generatedRoot . '/fail2ban/filter.d/mailpanel-webmail-auth.conf',
                    'content' => $webmailFilter,
                ],
            ],
        ];
    }

    private function safeAbsolutePath(string $path, string $label): string
    {
        $path = rtrim(trim($path), '/\\');
        $normalized = str_replace('\\', '/', $path);
        $isUnixAbsolute = str_starts_with($path, '/') && preg_match('/\A[\/A-Za-z0-9._-]+\z/', $path) === 1;
        $isWindowsAbsolute = preg_match('/\A[A-Za-z]:[\/\\\\A-Za-z0-9._~-]+\z/', $path) === 1;

        if ($path === '' || (!$isUnixAbsolute && !$isWindowsAbsolute) || $this->containsPathTraversal($normalized)) {
            throw new \InvalidArgumentException(sprintf('Invalid %s for Fail2ban config.', $label));
        }

        return $path;
    }

    private function containsPathTraversal(string $path): bool
    {
        $segments = array_values(array_filter(explode('/', $path), static fn (string $segment): bool => $segment !== ''));

        return in_array('..', $segments, true);
    }
}
