<?php

declare(strict_types=1);

namespace MailPanel\Services;

use MailPanel\Support\SafePath;

final class NginxConfigRenderer
{
    private readonly TlsCertificateInventory $tlsInventory;
    private readonly string $webmailPath;
    private readonly string $webmailPublicRoot;

    public function __construct(
        private readonly string $generatedRoot,
        private readonly string $nginxRoot = '/opt/mailpanel/public',
        private readonly string $serverName = '_',
        string $webmailPath = '/webmail',
        string $webmailPublicRoot = '/var/www/webmail',
        private readonly string $phpFpmSocket = '/run/php/php8.3-fpm.sock',
        private readonly string $defaultCertificate = '/etc/ssl/certs/ssl-cert-snakeoil.pem',
        private readonly string $defaultPrivateKey = '/etc/ssl/private/ssl-cert-snakeoil.key',
        private readonly string $acmeWebroot = '/var/www/acme',
        ?TlsCertificateInventory $tlsInventory = null,
    ) {
        $normalizedWebmailPath = '/' . trim($webmailPath, '/');
        $this->webmailPath = $this->safeLocationPath($normalizedWebmailPath === '/' ? '/webmail' : $normalizedWebmailPath);
        $normalizedWebmailRoot = rtrim(trim($webmailPublicRoot), '/');
        $this->webmailPublicRoot = $this->safeAbsolutePath($normalizedWebmailRoot !== '' ? $normalizedWebmailRoot : '/var/www/webmail', 'webmail public root');
        $this->tlsInventory = $tlsInventory ?? new TlsCertificateInventory();
    }

    public function render(): array
    {
        $generatedRoot = SafePath::absolute($this->generatedRoot, 'generated root');
        $serverName = $this->safeServerName(trim($this->serverName) === '' ? '_' : $this->serverName);
        $nginxRoot = $this->safeAbsolutePath($this->nginxRoot, 'nginx root');
        $acmeWebroot = $this->safeAbsolutePath($this->acmeWebroot, 'ACME webroot');
        $entries = $this->tlsInventory->entries();
        $defaultCertificate = $this->defaultCertificate;
        $defaultPrivateKey = $this->defaultPrivateKey;
        if ($serverName !== '_' && isset($entries[$serverName])) {
            $defaultCertificate = (string) ($entries[$serverName]['certificate'] ?? $defaultCertificate);
            $defaultPrivateKey = (string) ($entries[$serverName]['privatekey'] ?? $defaultPrivateKey);
        }
        $defaultCertificate = $this->safeAbsolutePath($defaultCertificate, 'default TLS certificate path');
        $defaultPrivateKey = $this->safeAbsolutePath($defaultPrivateKey, 'default TLS private key path');
        $tlsHosts = $this->renderTlsServerBlocks($this->tlsInventory->entries());
        $commonLocations = $this->renderCommonLocations();
        $content = strtr(<<<'CONF'
# generated by MailPanel
map "$request_method:$arg__task" $webmail_login_key {
    default "";
    "POST:login" $binary_remote_addr;
}

limit_req_zone $webmail_login_key zone=webmail_auth:10m rate=10r/m;

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name __SERVER_NAME__;
    root __NGINX_ROOT__;

    location ^~ /.well-known/acme-challenge/ {
        root __ACME_WEBROOT__;
        default_type text/plain;
        try_files $uri =404;
    }

    location = __WEBMAIL_PATH__ {
        return 308 __WEBMAIL_PATH__/;
    }

    location / {
        return 308 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    server_name __SERVER_NAME__;
    root __NGINX_ROOT__;
    index index.php;
    client_max_body_size 25m;

    ssl_certificate __DEFAULT_CERTIFICATE__;
    ssl_certificate_key __DEFAULT_PRIVATEKEY__;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

__COMMON_LOCATIONS__
}
__TLS_SERVER_BLOCKS__
CONF, [
            '__SERVER_NAME__' => $serverName,
            '__NGINX_ROOT__' => $nginxRoot,
            '__ACME_WEBROOT__' => $acmeWebroot,
            '__WEBMAIL_PATH__' => $this->webmailPath,
            '__WEBMAIL_PUBLIC_ROOT__' => $this->webmailPublicRoot,
            '__DEFAULT_CERTIFICATE__' => $defaultCertificate,
            '__DEFAULT_PRIVATEKEY__' => $defaultPrivateKey,
            '__COMMON_LOCATIONS__' => $commonLocations,
            '__TLS_SERVER_BLOCKS__' => $tlsHosts,
        ]);

        return [
            'service' => 'nginx',
            'path' => $generatedRoot . '/nginx/mailpanel.conf',
            'content' => rtrim($content) . "\n",
            'extras' => [],
        ];
    }

    private function renderCommonLocations(): string
    {
        $acmeWebroot = $this->safeAbsolutePath($this->acmeWebroot, 'ACME webroot');
        $phpFpmSocket = $this->safeAbsolutePath($this->phpFpmSocket, 'PHP-FPM socket');

        return strtr(<<<'CONF'
    location ^~ /.well-known/acme-challenge/ {
        root __ACME_WEBROOT__;
        default_type text/plain;
        try_files $uri =404;
    }

    location = __WEBMAIL_PATH__ {
        return 308 __WEBMAIL_PATH__/;
    }

    location = __WEBMAIL_PATH__/ {
        rewrite ^ __WEBMAIL_PATH__/index.php last;
    }

    location @mailpanel_webmail_index {
        rewrite ^ __WEBMAIL_PATH__/index.php last;
    }

    location ~ ^__WEBMAIL_PATH__/(?:config|data|temp|logs|installer|SQL|bin|vendor)/ {
        deny all;
    }

    location ~ ^__WEBMAIL_PATH__/(?:\.|README|CHANGELOG|UPGRADING|INSTALL|LICENSE|composer\.(?:json|lock)|Makefile) {
        deny all;
    }

    location __WEBMAIL_PATH__/ {
        alias __WEBMAIL_PUBLIC_ROOT__/;
        index index.php;
        try_files $uri $uri/ @mailpanel_webmail_index;
    }

    location ~ ^__WEBMAIL_PATH__/(.+\.php)(?:/|$) {
        fastcgi_pass unix:__PHP_FPM_SOCKET__;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME __WEBMAIL_PUBLIC_ROOT__/$1;
        fastcgi_param DOCUMENT_ROOT __WEBMAIL_PUBLIC_ROOT__;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "same-origin" always;
        # Roundcube renders inline script/style and some plugins use eval-like legacy JS.
        # Keep this relaxed policy scoped to the webmail PHP location only; the panel CSP remains strict.
        add_header Content-Security-Policy "default-src 'self'; img-src 'self' data: https: blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-src 'self' blob:; frame-ancestors 'self'; form-action 'self'" always;
    }

    location ^~ /qa/ {
        return 404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:__PHP_FPM_SOCKET__;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    }

    location ~ ^/(?:\.env|composer\.(?:json|lock)|database|config|storage|tests|docs)(?:/|$) {
        deny all;
    }
CONF, [
            '__ACME_WEBROOT__' => $acmeWebroot,
            '__WEBMAIL_PATH__' => $this->webmailPath,
            '__WEBMAIL_PUBLIC_ROOT__' => $this->webmailPublicRoot,
            '__PHP_FPM_SOCKET__' => $phpFpmSocket,
        ]);
    }

    private function renderTlsServerBlocks(array $entries): string
    {
        if ($entries === []) {
            return '';
        }

        $blocks = [];
        $commonLocations = $this->renderCommonLocations();
        $mainServerName = $this->safeServerName(trim($this->serverName) === '' ? '_' : $this->serverName);
        
        foreach ($entries as $hostname => $paths) {
            $hostname = $this->safeServerName((string) $hostname);
            
            // Skip rendering a duplicate block for the main portal domain
            if ($hostname === $mainServerName && $mainServerName !== '_') {
                continue;
            }
            
            $certificate = $this->safeAbsolutePath((string) ($paths['certificate'] ?? ''), 'TLS certificate path');
            $privateKey = $this->safeAbsolutePath((string) ($paths['privatekey'] ?? ''), 'TLS private key path');

            $blocks[] = strtr(<<<'CONF'

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name __HOSTNAME__;
    root __NGINX_ROOT__;
    index index.php;
    client_max_body_size 25m;

    ssl_certificate __CERTIFICATE__;
    ssl_certificate_key __PRIVATEKEY__;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

__COMMON_LOCATIONS__
}
CONF, [
                '__HOSTNAME__' => $hostname,
                '__NGINX_ROOT__' => $this->safeAbsolutePath($this->nginxRoot, 'nginx root'),
                '__CERTIFICATE__' => $certificate,
                '__PRIVATEKEY__' => $privateKey,
                '__COMMON_LOCATIONS__' => $commonLocations,
            ]);
        }

        return implode('', $blocks);
    }

    private function safeServerName(string $serverName): string
    {
        $serverName = trim($serverName);
        if ($serverName === '') {
            return '_';
        }

        $names = preg_split('/\s+/', $serverName) ?: [];
        foreach ($names as $name) {
            if ($name === '_' || preg_match('/\A(?:\*\.)?[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?\z/', $name) === 1) {
                continue;
            }

            throw new \InvalidArgumentException('Invalid server name for Nginx config.');
        }

        return implode(' ', $names);
    }

    private function safeLocationPath(string $path): string
    {
        if (preg_match('/\A\/[A-Za-z0-9][A-Za-z0-9\/_-]*\z/', $path) !== 1 || str_contains($path, '//')) {
            throw new \InvalidArgumentException('Invalid location path for Nginx config.');
        }

        return rtrim($path, '/') ?: '/webmail';
    }

    private function safeAbsolutePath(string $path, string $label): string
    {
        $path = rtrim(trim($path), '/');
        if ($path === '') {
            throw new \InvalidArgumentException(sprintf('Invalid %s for Nginx config.', $label));
        }

        if (preg_match('/\A\/[A-Za-z0-9._\/-]+\z/', $path) !== 1 || $this->containsPathTraversal($path)) {
            throw new \InvalidArgumentException(sprintf('Invalid %s for Nginx config.', $label));
        }

        return $path;
    }

    private function containsPathTraversal(string $path): bool
    {
        $segments = array_values(array_filter(explode('/', $path), static fn (string $segment): bool => $segment !== ''));

        return in_array('..', $segments, true);
    }
}
