<?php

declare(strict_types=1);

namespace MailPanel\Services;

final class RspamdConfigRenderer
{
    public function __construct(private readonly string $generatedRoot)
    {
    }

    public function render(): array
    {
        $generatedRoot = $this->safeAbsolutePath($this->generatedRoot, 'generated root');
        $content = <<<CONF
# generated by MailPanel
reject = 15;
add_header = 6;
greylist = 4;
CONF;

        $antivirus = <<<CONF
# generated by MailPanel
clamav {
  type = "clamav";
  symbol = "CLAM_VIRUS";
  servers = "/var/run/clamav/clamd.ctl";
  scan_mime_parts = true;
  action = "reject";
}
CONF;

        return [
            'service' => 'rspamd',
            'path' => $generatedRoot . '/rspamd/actions.conf',
            'content' => $content,
            'extras' => [
                [
                    'path' => $generatedRoot . '/rspamd/antivirus.conf',
                    'content' => $antivirus,
                ],
            ],
        ];
    }

    private function safeAbsolutePath(string $path, string $label): string
    {
        $path = rtrim(trim($path), '/\\');
        $normalized = str_replace('\\', '/', $path);
        $isUnixAbsolute = str_starts_with($path, '/') && preg_match('/\A[\/A-Za-z0-9._-]+\z/', $path) === 1;
        $isWindowsAbsolute = preg_match('/\A[A-Za-z]:[\/\\\\A-Za-z0-9._~-]+\z/', $path) === 1;

        if ($path === '' || (!$isUnixAbsolute && !$isWindowsAbsolute) || $this->containsPathTraversal($normalized)) {
            throw new \InvalidArgumentException(sprintf('Invalid %s for Rspamd config.', $label));
        }

        return $path;
    }

    private function containsPathTraversal(string $path): bool
    {
        $segments = array_values(array_filter(explode('/', $path), static fn (string $segment): bool => $segment !== ''));

        return in_array('..', $segments, true);
    }
}
